### ISSUE TITLE
FATAL:  Datasource helper (bladerf-wiphy)

### ISSUE THREAD

**Issue by l-jessie** [kismetwireless/kismet#512]
###
brew install --HEAD kismet-git

###
$ kismet -v  
     Kismet 2023-00-GIT
$ brew list --versions kismet-git  
     kismet-git HEAD-d51a5f5
###
macos 2019 intel core (Sonoma 14.3.1)

###Data Source
Interface | en0
Capture Driver | osxcorewlanwifi
Hardware | osxcorewlan
Type | Capture from OSX Wi-Fi devices using the CoreWLAN framework （internal Apple Wi-Fi devices）

###Continuous pop-up error alerts 
FATAL:  Datasource helper (bladerf-wiphy) failed, could not process incoming control packet.
FATAL:  Datasource helper (bladerf-wiphy) failed, could not process incoming control packet.
FATAL:  Datasource helper (bladerf-wiphy) failed, could not process incoming control packet.
FATAL:  Datasource helper (bladerf-wiphy) failed, could not process incoming control packet.
FATAL:  Datasource helper (bladerf-wiphy) failed, could not process incoming control packet.
.....
.....
.....

###
The first time you run it you don't get a prompt, but an error after clicking on the "Data Sources" popup window in the menu. 
I'm not sure if I'm missing something.
It seems to be working fine, but the red message is missing from the list.
But sometimes it also stays at "Kismet is probing for available capture interfaces..." , you need to kill the server and reboot.
--

**Comment by l-jessie** [comment]
FATAL:  Datasource helper (bladerf-wiphy) failed, could not process incoming control packet.
Traceback (most recent call last):
  File "/usr/local/bin/kismet_cap_sdr_rtl433", line 33, in <module>
    sys.exit(load_entry_point('KismetCaptureRtl433==2020.10.1', 'console_scripts', 'kismet_cap_sdr_rtl433')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/kismet_cap_sdr_rtl433", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/local/lib/python3.12/site-packages/KismetCaptureRtl433/__init__.py", line 33, in <module>
    from . import kismetexternal
  File "/usr/local/lib/python3.12/site-packages/KismetCaptureRtl433/kismetexternal/__init__.py", line 33, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'

**Comment by l-jessie** [comment]
File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/usr/local/lib/python3.12/site-packages/KismetCaptureRtlamr/__init__.py", line 39, in <module>
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/local/lib/python3.12/site-packages/KismetCaptureRtladsb/__init__.py", line 38, in <module>
    from . import kismetexternal
    from . import kismetexternal
  File "/usr/local/lib/python3.12/site-packages/KismetCaptureRtlamr/kismetexternal/__init__.py", line 33, in <module>
  File "/usr/local/lib/python3.12/site-packages/KismetCaptureRtladsb/kismetexternal/__init__.py", line 33, in <module>
    import websockets
    import websockets
ModuleNotFoundError: No module named 'websockets'
ModuleNotFoundError: No module named 'websockets'
