### ISSUE TITLE
KismetRest - Request Failed for POST 400

### ISSUE THREAD

**Issue by ryanvillarreal** [kismetwireless/kismet#74]
I'm having problems when attempting to set a locked channel on a device by passing the UUID, and the channel to the Rest API.  

`def set_kismet_listener(iface,channel,username,passwd):
	kr = KismetRest.KismetConnector(uri)
	kr.set_login(username,passwd)
	kr.set_debug(True)

	if not kr.check_session():
	    sys.exit(1)

	datasources = kr.datasources()
	for ds in datasources:
		if iface == ds['kismet.datasource.name']:
			# print ("UUID: {}".format(ds['kismet.datasource.uuid']))
			iface_uuid = ds['kismet.datasource.uuid']

	"""
	Currenly getting an error message:
	KismetRest.KismetRequestException: Request failed for POST 
	datasource/by-uuid/5fe308bd-0000-0000-0000-5e7ddae9ea1e/set_channel.cmd 400
	"""
	kr.config_datasource_set_channel(iface_uuid,channel)`

Python output is as follows: 

`('Request failed:', 400)
Traceback (most recent call last):
  File "core.py", line 232, in <module>
    set_kismet_listener('wlan0',1,username,passwd)	
  File "core.py", line 218, in set_kismet_listener
    kr.config_datasource_set_channel(iface_uuid,channel)
  File "build/bdist.linux-x86_64/egg/KismetRest/__init__.py", line 624, in config_datasource_set_channel
    
  File "build/bdist.linux-x86_64/egg/KismetRest/__init__.py", line 402, in __post_string_url
    
KismetRest.KismetRequestException: Request failed for POST datasource/by-uuid/5fe308bd-0000-0000-0000-6abb92192cba/set_channel.cmd 400
`
I looked through issue #32 and it might be similar to my issue, but wanted to make sure I wasn't missing something first.

**Comment by ryanvillarreal** [comment]
Any update on this?  or should I just revert to the stable version of Kismet?

**Comment by ryanvillarreal** [comment]
Seems to be fixed.
